# Generated by Django 5.0.1 on 2024-03-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ctr",
            name="ad",
        ),
        migrations.RemoveField(
            model_name="ctr",
            name="clicks",
        ),
        migrations.AddField(
            model_name="ctr",
            name="adid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ctr",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="createad",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="createad",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="createad",
            name="offer_price",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="createad",
            name="price",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ctr",
            name="user_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
