# Generated by Django 5.0.1 on 2024-03-16 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_ctr_ad_remove_ctr_clicks_ctr_adid_ctr_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ctr",
            old_name="adid",
            new_name="UserName",
        ),
        migrations.RenameField(
            model_name="ctr",
            old_name="user_name",
            new_name="addId",
        ),
    ]
