# Generated by Django 5.0.1 on 2024-03-16 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_rename_adid_ctr_username_rename_user_name_ctr_addid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CreateAd",
            new_name="Adds",
        ),
        migrations.RenameField(
            model_name="ctr",
            old_name="email",
            new_name="Email",
        ),
    ]
